# Generated by Django 4.0.4 on 2022-07-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusuario', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=200)),
                ('aporte', models.IntegerField(default=0)),
                ('idcurso', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=200)),
                ('metacurso', models.IntegerField(default=0)),
            ],
        ),
    ]
